version: "3"
services:
  # core_api:
  #   build:
  #     context: .
  #   container_name: "core-api-container"
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./src:/src
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresql
    ports:
      - 5432:5432
