"""empty message

Revision ID: 06c33d8b15a0
Revises: 
Create Date: 2022-06-04 16:07:59.971884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c33d8b15a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserModel_email'), 'UserModel', ['email'], unique=True)
    op.create_index(op.f('ix_UserModel_id'), 'UserModel', ['id'], unique=False)
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    op.create_table('sostav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredients', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredients'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sostav_id'), 'sostav', ['id'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('sostav', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sostav'], ['sostav.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_sostav_id'), table_name='sostav')
    op.drop_table('sostav')
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_UserModel_id'), table_name='UserModel')
    op.drop_index(op.f('ix_UserModel_email'), table_name='UserModel')
    op.drop_table('UserModel')
    # ### end Alembic commands ###
