"""empty message

Revision ID: 1d67ced85c83
Revises: 06c33d8b15a0
Create Date: 2022-06-06 11:56:59.045764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d67ced85c83'
down_revision = '06c33d8b15a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_sostav_fkey', 'menu', type_='foreignkey')
    op.drop_column('menu', 'sostav')
    op.add_column('sostav', sa.Column('menu', sa.Integer(), nullable=True))
    op.add_column('sostav', sa.Column('amount', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sostav', 'menu', ['menu'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sostav', type_='foreignkey')
    op.drop_column('sostav', 'amount')
    op.drop_column('sostav', 'menu')
    op.add_column('menu', sa.Column('sostav', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('menu_sostav_fkey', 'menu', 'sostav', ['sostav'], ['id'])
    # ### end Alembic commands ###
